name: "amass"
description: "The OWASP Amass Project performs network mapping of attack surfaces and external asset discovery using open source information gathering and active reconnaissance techniques"
branding:
  icon: "activity"
  color: "blue"

inputs:

  output:
    description: "File to save output result"
    required: false
    default: "amass-result.txt"   

  config:
    description: "Path to the INI configuration file."
    required: true     


runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/amass ] && cd  /home/runner && wget https://github.com/owasp-amass/amass/releases/download/v3.23.3/amass_Linux_amd64.zip && unzip amass_Linux_amd64.zip && ls -al /home/runner/amass_Linux_amd64 && pwd
      shell: bash

    - run: |
        /home/runner/amass_Linux_amd64/amass enum -src -config=${{ inputs.config }} -o=${{ inputs.output }}      
      shell: bash
